=== anastasiyakibisova/course_pvt/project/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Refs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Authentication">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Site" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="Login"/>
                    <xs:element type="xs:string" name="Password"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== anastasiyakibisova/course_pvt/project/Authentication.xml
<?xml version="1.0" encoding="UTF-8"?>
<Refs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Schema.xsd">
	<Authentication>
		<Site id="1">
			<Name>https://mail.ru/</Name>
			<Login>anastasiyakibisova</Login>
			<Password>7896791qaz</Password>
		</Site>
		<Site id="2">
			<Name>https://vk.com</Name>
			<Login>***********</Login>
			<Password>*********</Password>
		</Site>
	</Authentication>
</Refs>
